{{- if .Values.networkPolicy.enabled }}
# Network Policy
# Implements network segmentation and zero-trust security
# Controls which pods can communicate with the application
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "embassy-appointments.fullname" . }}
  labels:
    {{- include "embassy-appointments.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "embassy-appointments.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  {{- if .Values.networkPolicy.ingress }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  {{- end }}
  {{- if .Values.networkPolicy.egress }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
  {{- end }}
{{- end }}
