{{- if .Values.podDisruptionBudget.enabled }}
# Pod Disruption Budget
# Ensures minimum number of pods remain available during voluntary disruptions
# Prevents service outages during rolling updates or node maintenance
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "embassy-appointments.fullname" . }}
  labels:
    {{- include "embassy-appointments.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "embassy-appointments.selectorLabels" . | nindent 6 }}
{{- end }}
