{{- if .Values.persistence.enabled }}
# Persistent Volume Claim
# Requests storage for the SQLite database
# Persists appointment data across pod restarts and redeployments
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "embassy-appointments.fullname" . }}-data
  labels:
    {{- include "embassy-appointments.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  storageClassName: {{ .Values.persistence.storageClass | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }}
