# Secret Resource
# Stores sensitive configuration (API keys, passwords, etc.)
# Values are base64-encoded and encrypted at rest in etcd
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "embassy-appointments.fullname" . }}
  labels:
    {{- include "embassy-appointments.labels" . | nindent 4 }}
type: Opaque
data:
  SECRET_KEY: {{ .Values.secrets.secretKey | b64enc | quote }}
  {{- if .Values.secrets.databasePassword }}
  DATABASE_PASSWORD: {{ .Values.secrets.databasePassword | b64enc | quote }}
  {{- end }}
