{{- if .Values.serviceMonitor.enabled }}
# ServiceMonitor (Prometheus Operator)
# Configures Prometheus to scrape metrics from the application
# Enables monitoring of application performance and health
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "embassy-appointments.fullname" . }}
  labels:
    {{- include "embassy-appointments.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "embassy-appointments.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: {{ .Values.serviceMonitor.interval }}
    scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
{{- end }}
